spring:
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: mail.golfpvcc.com
    username: MagaMan@golfpvcc.com

jwt:
  expirationMinutes: 1000

nginx:
  require-proxy: false

peep:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
