spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: vinnie@sandbox93322efb7ef84e38a3482d94bd7a3d52.mailgun.org

jwt:
  expirationMinutes: 1000

nginx:
  require-proxy: false

peep:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
